#!/usr/bin/env python3
"""
TicketOps Build & Packaging Script

Commands:
    python build.py setup                 Install all dependencies
    python build.py package               Bundle into a distributable executable
    python build.py package --platform X  Target platform hint (win/mac/linux)
    python build.py clean                 Remove build artifacts

Requirements for packaging:
    pip install pyinstaller>=6.0.0
"""

import argparse
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent
DESKTOP_DIR = ROOT_DIR / "desktop"
DIST_DIR = ROOT_DIR / "dist"
BUILD_DIR = ROOT_DIR / "build"
SPEC_FILE = ROOT_DIR / "ticketops.spec"

APP_NAME = "TicketOps"

# Python modules to include in the bundle (all .py files except helpers/build).
EXCLUDE_FILES = {"build.py", "create_test_video.py", "start.py", "run.py"}

# Large packages to exclude from the PyInstaller bundle to reduce size.
PYINSTALLER_EXCLUDES = [
    "matplotlib",
    "tkinter",
    "scipy.spatial.cKDTree",
    "IPython",
    "jupyter",
    "jupyter_client",
    "jupyter_core",
    "notebook",
    "nbconvert",
    "nbformat",
    "pytest",
    "unittest",
    "setuptools",
    "pip",
    "distutils",
    "ensurepip",
    "pydoc_data",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run(cmd, cwd=None, check=True):
    """Run a command, printing it first."""
    label = " ".join(str(c) for c in cmd)
    print(f"\n>>> {label}")
    result = subprocess.run(cmd, cwd=cwd)
    if check and result.returncode != 0:
        print(f"[ERROR] Command failed with exit code {result.returncode}")
        sys.exit(result.returncode)
    return result.returncode


def ensure_command(name, install_hint=""):
    """Check that a CLI tool is available on PATH."""
    if shutil.which(name):
        return True
    msg = f"[WARN]  '{name}' not found."
    if install_hint:
        msg += f" {install_hint}"
    print(msg)
    return False


def generate_spec_file():
    """Generate the ticketops.spec file dynamically if it does not exist."""
    if SPEC_FILE.exists():
        print(f"[INFO]  Using existing spec file: {SPEC_FILE}")
        return

    print(f"[INFO]  Generating spec file: {SPEC_FILE}")

    # Discover .py modules
    py_files = sorted(
        p for p in ROOT_DIR.glob("*.py")
        if p.name not in EXCLUDE_FILES
        and p.name != "ticketops.spec"
        and p.name != "__pycache__"
    )
    hidden_imports = [p.stem for p in py_files if p.stem != "app"]

    excludes_str = ",\n    ".join(f'"{e}"' for e in PYINSTALLER_EXCLUDES)
    hidden_str = ",\n    ".join(f'"{h}"' for h in hidden_imports)

    spec_content = textwrap.dedent(f'''\
        # -*- mode: python ; coding: utf-8 -*-
        """
        PyInstaller spec file for TicketOps — auto-generated by build.py
        """
        import sys
        from pathlib import Path

        ROOT = Path(SPECPATH)

        hiddenimports = [
            {hidden_str}
        ]

        datas = []
        if (ROOT / "config.py").exists():
            datas.append((str(ROOT / "config.py"), "."))
        if (ROOT / "templates").is_dir():
            datas.append((str(ROOT / "templates"), "templates"))
        if (ROOT / "static").is_dir():
            datas.append((str(ROOT / "static"), "static"))
        if (ROOT / "desktop" / "assets" / "icon.svg").exists():
            datas.append((str(ROOT / "desktop" / "assets" / "icon.svg"), "assets"))

        excludes = [
            {excludes_str}
        ]

        a = Analysis(
            [str(ROOT / "app.py")],
            pathex=[str(ROOT)],
            binaries=[],
            datas=datas,
            hiddenimports=hiddenimports,
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=excludes,
            noarchive=False,
        )

        pyz = PYZ(a.pure)

        exe = EXE(
            pyz,
            a.scripts,
            [],
            exclude_binaries=True,
            name="{APP_NAME}",
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            console=False if sys.platform == "win32" else True,
            icon=None,
        )

        coll = COLLECT(
            exe,
            a.binaries,
            a.datas,
            strip=False,
            upx=True,
            upx_exclude=[],
            name="{APP_NAME}",
        )
    ''')

    SPEC_FILE.write_text(spec_content)
    print(f"[INFO]  Spec file written to {SPEC_FILE}")


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_setup():
    """Install Python requirements and desktop (npm) dependencies."""
    print("=" * 60)
    print("  TicketOps — Setup")
    print("=" * 60)

    # Python deps
    req_file = ROOT_DIR / "requirements.txt"
    if req_file.exists():
        run([sys.executable, "-m", "pip", "install", "-r", str(req_file)])
    else:
        print("[WARN]  requirements.txt not found, skipping Python deps")

    # Desktop (Electron) deps
    pkg_json = DESKTOP_DIR / "package.json"
    if pkg_json.exists():
        if ensure_command("npm", "Install Node.js from https://nodejs.org"):
            run(["npm", "install"], cwd=DESKTOP_DIR)
        else:
            print("[WARN]  Skipping Electron deps (npm not available)")
    else:
        print("[INFO]  No desktop/package.json found — skipping Electron deps")

    print("\n[DONE]  Setup complete.\n")


def cmd_package(platform=None):
    """Bundle the Python backend into a distributable using PyInstaller."""
    print("=" * 60)
    print("  TicketOps — Package")
    print("=" * 60)

    # Ensure PyInstaller is installed.
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("[INFO]  PyInstaller not found. Installing ...")
        run([sys.executable, "-m", "pip", "install", "pyinstaller>=6.0.0"])

    if platform:
        print(f"[INFO]  Target platform hint: {platform}")
        print("[NOTE]  PyInstaller can only build for the current OS.")
        print("[NOTE]  Use a CI matrix (GitHub Actions) for true cross-platform builds.\n")

    # Generate spec file if missing.
    generate_spec_file()

    # Run PyInstaller.
    cmd = [
        sys.executable, "-m", "PyInstaller",
        str(SPEC_FILE),
        "--noconfirm",
        "--clean",
    ]

    print(f"[INFO]  Spec file: {SPEC_FILE}")
    run(cmd, cwd=ROOT_DIR)

    # Report output location and size.
    out_dir = DIST_DIR / APP_NAME
    if out_dir.exists():
        size_mb = sum(
            f.stat().st_size for f in out_dir.rglob("*") if f.is_file()
        ) / (1024 * 1024)
        print(f"\n[DONE]  Build complete: {out_dir}")
        print(f"[INFO]  Total size: {size_mb:.1f} MB")
    else:
        suffix = ".exe" if sys.platform == "win32" else ""
        exe = DIST_DIR / (APP_NAME + suffix)
        if exe.exists():
            size_mb = exe.stat().st_size / (1024 * 1024)
            print(f"\n[DONE]  Build complete: {exe}")
            print(f"[INFO]  Size: {size_mb:.1f} MB")
        else:
            print(f"\n[DONE]  Build finished. Check {DIST_DIR}/ for output.")


def cmd_clean():
    """Remove build artifacts."""
    print("=" * 60)
    print("  TicketOps — Clean")
    print("=" * 60)

    for d in (BUILD_DIR, DIST_DIR):
        if d.exists():
            print(f"[INFO]  Removing {d}")
            shutil.rmtree(d)

    # Remove __pycache__ dirs
    for cache_dir in ROOT_DIR.rglob("__pycache__"):
        if cache_dir.is_dir():
            shutil.rmtree(cache_dir)
            print(f"[INFO]  Removed {cache_dir}")

    # Remove generated .spec if desired (keep it — user may have customised)
    print("\n[DONE]  Clean complete.\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="TicketOps build & packaging tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python build.py setup
              python build.py package
              python build.py package --platform win
              python build.py clean
        """),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("setup", help="Install Python and npm dependencies")

    pkg = sub.add_parser("package", help="Create distributable executable")
    pkg.add_argument(
        "--platform", choices=["win", "mac", "linux"], default=None,
        help="Target platform hint (informational only; PyInstaller builds for current OS)",
    )

    sub.add_parser("clean", help="Remove build artifacts")

    args = parser.parse_args()

    if args.command == "setup":
        cmd_setup()
    elif args.command == "package":
        cmd_package(platform=args.platform)
    elif args.command == "clean":
        cmd_clean()


if __name__ == "__main__":
    main()
